spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

algamoney:
  seguranca:
    enable-https: true    
  origin-permitida:  https://algamoney-angular.railway.com