spring:
  database: MYSQL
  datasource:
    url: jdbc:mysql://algamoneydb.cabbosts295g.sa-east-1.rds.amazonaws.com:3306/algamoneybd?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: administrador
  
algamoney:
  seguranca:
    enable-https: false
    
