spring:
  database: MYSQL
  datasource:
    url: jdbc:mysql://database-algamoney.cabbosts295g.sa-east-1.rds.amazonaws.com
    username: database-algamoney
    password: administrador
  
algamoney:
  seguranca:
    enable-https: false
    
