spring:
  database: MYSQL
  datasource:
    url: jdbc:mysql://localhost/algamoneyapi?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
